<?xml version="1.0"?>
<package format="3">
  <name>simulation</name>
  <version>0.0.1</version>
  <description>Gazebo simulation assets for the CPR project</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>ros_gz_sim</depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>alignment</exec_depend>
  <exec_depend>rear_ackermann_controller</exec_depend>
  <exec_depend>shoulder_align_controller</exec_depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
