hwt9053_imu:
  ros__parameters:
    port: /dev/imu_usb
    baudrate: 115200
    protocol: RS485_HIGH
    modbus_id: 80  # 0x50, unit8_t로 변환해 Modbus가 전송할 것임
    frame_id: imu_link
    relative_orientation: true
    response_timeout_ms: 50
