<?xml version="1.0"?>
<package format="3">
  <name>vision</name>
  <version>0.0.1</version>
  <description>RealSense D435, MediaPipe Pose, shoulder filtering, and RViz tools.</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>
  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>rviz2</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
